### ISSUE TITLE
Footer-icons section

### ISSUE THREAD

**Issue by Grumstukas** [front-end-by-rimantas/8-grupe-portfolio-warg#21]
- [x] social icons (using JS)
- [x] back to top button-link
- [x] Responsive design

**Comment by mayankpawar25** [comment]
social icons using js means?
Responsive Design is for footer only?

**Comment by Grumstukas** [comment]
1. Social icons using js means - we should figure out how to create social icons list/array using JavaScript.
2. No, responsive design isn't for footer only.
We are still learning, and this is our first project on which we are working in teams.
Thank you for your concern :)
